### ISSUE TITLE
Bug: Initialization check for timeout most likely incorrect

### ISSUE THREAD

**Issue by casbeebc** [Abenity/abenity-php#1]
Looks like a copy/paste issue with the initialization for `timeout`. Checks if `timeout` is numeric then sets `version`, instead of checking if `version` is numeric. 

[Line 68](https://github.com/Abenity/abenity-php/blob/master/lib/Abenity/ApiClient.php#L68)

**Comment by markroland** [comment]
Thanks for catching this and fixing!
